nav:
  - Home: index.md
  - Foundations:
      - Overview: foundations/index.md
  - Market Risk:
      - Overview: market_risk/index.md
      - Value at Risk (VaR): market_risk/var.md
  - Case Studies:
      - Overview: cases/index.md
      - LTCM: cases/ltcm.md

